name: Check for Upstream Release

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  check-release:
    runs-on: ubuntu-latest
    outputs:
      sync-needed: ${{ steps.detect.outputs.sync-needed }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests toml pyyaml packaging

      - name: Run check script
        id: detect
        run: |
          result=0
          python .github/scripts/check_upstream_release.py || result=$?

          if [ "$result" -eq 42 ]; then
            echo "New upstream version detected"
            echo "sync-needed=true" >> $GITHUB_OUTPUT
          elif [ "$result" -eq 0 ]; then
            echo "No new upstream release"
            echo "sync-needed=false" >> $GITHUB_OUTPUT
          else
            echo "Script failed (exit code $result)"
            exit $result
          }