name: Conventional PRs
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  title-format:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          config: .github/pr-types.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
