# .github/workflows/release.yml
name: PyPI Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'           # when a tag like v1.2.3 or v1.2.3.post2 is pushed
  workflow_dispatch:      # allow manual runs from the Actions UI

jobs:
  bump-and-tag:
    name: Bump version & Tag
    # Only run on:
    #  • manual dispatch, OR
    #  • pushes to main that have “[bump]” in the commit message
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'push' &&
       startsWith(github.ref, 'refs/heads/main') &&
       contains(github.event.head_commit.message, '[bump]'))
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python & Poetry
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install poetry

      - name: Compute next post-release version
        id: bump
        run: |
          FULL=$(poetry version -s)
          UPSTREAM="${FULL%%.post*}"
          if [[ $FULL =~ \.post([0-9]+)$ ]]; then
            NEXT=$((BASH_REMATCH[1] + 1))
          else
            NEXT=1
          fi
          NEW="${UPSTREAM}.post${NEXT}"
          poetry version "$NEW"
          echo "New version: $NEW"
          echo "new_version=$NEW" >> "$GITHUB_OUTPUT"

      - name: Commit bumped version
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Version ${{ steps.bump.outputs.new_version }}"

      - name: Tag release
        run: |
          echo "Tagging v${{ steps.bump.outputs.new_version }} 
          git tag "v${{ steps.bump.outputs.new_version }}"

      - name: Push commit & tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD
          git push origin "v${{ steps.bump.outputs.new_version }}"

  publish:
    name: Build & Publish to PyPI
    # Only run when a tag is pushed (not on main-branch pushes or manual dispatch)
    if: github.event_name == 'push' && 
        startsWith(github.ref, 'refs/tags/v') &&
        false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build tools
        run: pip install build twine

      - name: Build distributions
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
