on:
  workflow_run:
    workflows: ["Check for Upstream Release"]
    types:
      - completed

jobs:
  sync:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download workflow artifacts
        uses: dawidd6/action-download-artifact@v3

      - name: Download upstream-version output
        id: get-outputs
        uses: actions/github-script@v7
        with:
          script: |
            const runId = context.payload.workflow_run.id;
            const resp = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: runId
            });

            const outputs = resp.data.outputs || {};
            return {
              version: outputs["upstream-version"] ?? "unknown"
            };
        result-encoding: string

      - name: Checkout fork
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/snakemake/snakemake-executor-plugin-slurm-jobstep
          git fetch upstream

      - name: Create sync branch
        run: |
          BRANCH="sync-upstream-$(date +'%Y%m%d')"
          git checkout -b $BRANCH upstream/main
          git push origin $BRANCH

      - name: Open PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: sync-upstream-$(date +'%Y%m%d')
          title: "Sync with upstream release v${{ steps.get-outputs.outputs.version }}"
          body: "This PR was auto-generated to sync with upstream version v${{ steps.get-outputs.outputs.version }}."